# Default values for deployment, this is necessary because we're using a unified helm subchart
deployment:
  replicas: 1

  image:
    repository: 534042329084.dkr.ecr.us-east-1.amazonaws.com/developers/discord_gm_bot

  # This is the name of the deployment, this is used in a _lot_ of places in the helm charts so lets just specify it
  name: discord-gm-bot

  deploymentStrategy:
    type: Recreate

  # Environment variables
  globalEnvs:
    - name: DISCORD_TOKEN
      valueFrom:
        secretKeyRef:
          name: discord-gm-secret
          key: DISCORD_TOKEN

  # livenessProbes are used to determine when to restart a container
  # Only specify the values you need to override from the defaults
  livenessProbe:
    enabled: false

  # readinessProbes are used to determine when a container is ready to start accepting traffic
  # Only specify the values you need to override from the defaults
  readinessProbe:
    enabled: false

  service:
    targetPort: 3000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "developers"
    # hosts:
    #   - host: discord-gm-bot.exodus-local.io
    #     paths:
    #       - /

  # deployment container resource requests/limits
  # this is set VERY low by default, to be aggressive above resource limiting, please override this if necessary
  # Note: Limits are HARD Limits
  #       Requests are "soft" limits and are what affects HPA (autoscaling) aggressiveness if HPA is enabled
  resources:
    requests:
      cpu: 5m
      memory: 40M

  nodeSelector:
    kubernetes.io/arch: arm64

  tolerations:
    # because we want it to run on arm64 nodes as well
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoExecute"
